apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      name: calc
      labels:
        app: calc
    spec:
      containers:
        - name: calc
          image: ghcr.io/eclipse-ee4j/calc:v2.2-SNAPSHOT
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: calc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: calc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calc
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calc
                port:
                  number: 80